/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StringDiziPaketi;

import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author tunca
 */
public class stringDiziJFrame extends javax.swing.JFrame {

    /**
     * Creates new form stringDiziJFrame
     */
    public stringDiziJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jButton1.setText("(0.0-1.0) arasında ondalık ve (0-100) Arasında tam sayı Üret");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel2.setText("Bir sayı dizisi oluşturalım, kaç elemanı olsun?");

        jButton2.setText("Oluştur");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");

        jLabel3.setText("jLabel3");

        jButton3.setText("Array sınıfı ile dizileri sıralayalım ve karşılaştıralım");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // jframeform açıldığında çağırılan metot
        String mesaj;
        mesaj = "<html><h1>Merhaba Dünya</h1>" 
                + "<h2>pi sayısı : " + Math.PI + "</h2>"
                + "<h3>Doğal logaritma ln(x) in tabanı: " + Math.E 
                + "<p>Genel/Global değişkenler artol biliyoruz ki Class/Sınıfın field/alanları</p></h3></html>";
        jLabel1.setText(mesaj);
        jTextField1.setText("");
    }//GEN-LAST:event_formWindowOpened

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // butona mouse click olunca (0.0-1.0) arasında ondalık ve (0-100) Arasında tam sayı Üret
        double rastgele = Math.random();
        float rast = (float) rastgele;
        int tamsayi = Math.round(rast*100);
        jLabel1.setText("<html><p>(0.0-1.0) arasında ondalık rastgele sayı: " + rastgele +
                "</p>" + "<p>(0-100) Arasında tam sayı:" + tamsayi + "</p></html>");
    }//GEN-LAST:event_jButton1MouseClicked
    
    // Sınıfın field/alanları : 
    int dizi[];
    int adet;
    int i=-1;  // sayaç
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // bir sayı dizisi oluşturalım
        // bu buton 3 farklı şekilde çalışsın
        // 1) önce elemanlarının adeti verilen diziyi yaratalım
        // 2) ekeman sayısı adet kadar sayıyı diziye eklesin
        // 3) dizi ekrana yazsın ve yeni dizi için başa dönsün
        
        if (i<0) { // eleman sayısını al ve diziyi oluştur
            adet = Integer.parseInt(jTextField1.getText());
            dizi = new int[adet]; // adet tane 4 baytlık yer ayır bellekten
            i++;
            jLabel2.setText("Dizinin " + (i+1) + ". elemanını:");
            jButton2.setText("Ekleyiniz");
        }
        else if(i<adet){ // diziye elemanları ekle. jtextfield1 den oku.
            Integer sayi = Integer.parseInt(jTextField1.getText());
            dizi[i] = sayi;
            i++;
            jLabel2.setText("Dizinin " + (i+1) + ". elemanını:");
            jButton2.setText("Ekleyiniz");
        }
        if(i>=adet) { // else{  // diziyi ekrana bas yeni dizi kurmaya hazırla
            String mesaj = "<html><ol>";
            // enhenced for / iyileştirilmiş for döngüsü c# foreach oluyor
            // dizinin ilk elemanından son elemanına dönmeyi sağlar
            for (Integer d : dizi) {
                mesaj += "<li> eleman " + d.toString() + "</li>";
            }
            mesaj += "</ol></html>";
            jLabel3.setText(mesaj);
            // yeni dizi oluşturmak için başa dön
            i=-1;
            jLabel2.setText("Bir sayı dizisi oluşturalım kaç elemanı olsun?");
            jButton2.setText("Oluştur");
        }
        // Temizle
        jTextField1.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Array sınıfı ile dizileri sıralayalım ve karşılaştıralım
        String mesaj = "";
        int dizi[] = {3,8,5,7,6,4};
        // diziyi küçükten büyüğe sıralayalım
        Arrays.sort(dizi);
        // dizinin elemanlarını mesaja alıp mesajkutusunda gösterelim
        for(int sayi : dizi){
            mesaj += sayi + ", ";
        }
        JOptionPane.showMessageDialog(rootPane, mesaj);
        
        int dizi2[] = {8,3,5,7,6,4};
        // karşılaştıralım
        boolean b = Arrays.equals(dizi, dizi2);
        // eşitlik operatörü ile mesaj
        mesaj =(b)? "DENK":"DENK DEĞİL";
        JOptionPane.showMessageDialog(rootPane, mesaj);
        // eğer sıra önemli değilse elemanların kümede olması yeterli ise
        // iki diziyi sıralayıp öyle karşılaştıralım
        Arrays.sort(dizi);
        Arrays.sort(dizi2);
        b = Arrays.equals(dizi, dizi2);
        mesaj =(b)? "DENK":"DENK DEĞİL";
        JOptionPane.showMessageDialog(rootPane, mesaj);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stringDiziJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stringDiziJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stringDiziJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stringDiziJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stringDiziJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
